title: Magnus Tryggvason # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
theme: jekyll-theme-minimal
description: Hi there, my name is Magnus. I enjoy doing online shenanigans mostly using Javascript. I currently work as a Creative Technologist for [KISKA](https://kiska.com).
